import { test, expect, Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';

async function openApp(page: Page) { await page.goto('/'); const onboarding = page.getByRole('heading', { name: 'Build your English habit' }); if (await onboarding.isVisible().catch(() => false)) { await page.getByLabel('Your name').fill('Mali'); await page.getByRole('button', { name: 'Start learning' }).click(); } }

test('onboarding persists a learner profile and goal', async ({ page }) => { await page.goto('/'); if (await page.getByRole('heading', { name: 'Build your English habit' }).isVisible().catch(() => false)) { await page.getByLabel('Your name').fill('Nok'); await page.getByLabel('Current level').selectOption('B1'); await page.getByLabel('Learning goal').selectOption({ label: 'Travel English' }); await page.getByLabel('Daily goal').selectOption('15'); await page.getByRole('button', { name: 'Start learning' }).click(); } await expect(page.getByText('Welcome back')).toBeVisible(); await page.reload(); await expect(page.getByText('Nok')).toBeVisible(); });

test('app exposes the complete lesson library', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Learn', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Choose your next lesson' })).toBeVisible(); await expect(page.locator('.lesson-card')).toHaveCount(30); });

test('lesson completion is idempotent and persists', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Continue learning' }).click(); await page.getByRole('button', { name: 'Hide transcript' }).click(); await page.getByRole('button', { name: 'Show transcript' }).click(); await page.getByRole('button', { name: 'Complete lesson' }).click(); await expect(page.getByText('+20 XP added')).toBeVisible(); await page.reload(); await expect(page.getByText('20')).toBeVisible(); await page.getByRole('button', { name: 'Continue learning' }).click(); await page.getByRole('button', { name: 'Complete lesson' }).click(); await expect(page.getByText('Lesson already completed')).toBeVisible(); });

test('placement derives total and per-skill scores', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Placement', exact: true }).click(); await page.getByRole('button', { name: 'Start test' }).click(); for (let i = 0; i < 28; i++) { await page.locator('.answers button').first().click(); await page.getByRole('button', { name: i === 27 ? 'See result' : 'Next question' }).click(); } await expect(page.getByText(/weighted points/)).toBeVisible(); await expect(page.getByText(/Vocabulary \d+%/)).toBeVisible(); await page.getByRole('button', { name: 'Start learning' }).click(); await expect(page.getByText('Welcome back')).toBeVisible(); });

test('speaking fallback remains usable without microphone permissions', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Practice', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Find your speaking voice' })).toBeVisible(); await page.getByRole('button', { name: /Record my voice/ }).click(); await expect(page.getByRole('status')).toBeVisible(); });

test('MediaRecorder lifecycle supports record, stop, playback and delete', async ({ page }) => { await page.addInitScript(() => { class FakeRecorder { ondataavailable: (event: { data: Blob }) => void = () => {}; onstop: () => void = () => {}; state = 'inactive'; stream = { getTracks: () => [{ stop: () => {} }] }; mimeType = 'audio/webm'; start() { this.state = 'recording'; this.ondataavailable({ data: new Blob(['audio/webm'], { type: 'audio/webm' }) }); } stop() { this.state = 'inactive'; this.onstop(); } } Object.defineProperty(navigator, 'mediaDevices', { value: { getUserMedia: async () => ({ getTracks: () => [{ stop: () => {} }] }) } }); Object.defineProperty(window, 'MediaRecorder', { value: FakeRecorder, writable: true }); }); await openApp(page); await page.getByRole('button', { name: 'Practice', exact: true }).click(); await page.getByRole('button', { name: 'Record my voice' }).click(); await expect(page.getByRole('button', { name: /Stop recording/ })).toBeVisible(); await page.getByRole('button', { name: /Stop recording/ }).click(); await expect(page.locator('audio')).toBeVisible(); await page.getByRole('button', { name: 'Delete recording' }).click(); await expect(page.locator('audio')).toHaveCount(0); });

test('settings persist selected daily goal', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Settings', exact: true }).click(); await page.getByRole('button', { name: '20 min' }).click(); await page.reload(); await page.getByRole('button', { name: 'Settings', exact: true }).click(); await expect(page.getByRole('button', { name: '20 min' })).toHaveClass(/selected/); });

test('reading rejects wrong answers and vocabulary review persists', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Reading', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Ordering Coffee' })).toBeVisible(); await page.getByRole('button', { name: 'a small coffee with milk' }).click(); await expect(page.getByText('Correct.')).toBeVisible(); await page.getByRole('button', { name: 'a large tea' }).click(); await expect(page.getByText('Try again.')).toBeVisible(); await page.getByRole('button', { name: 'Vocabulary 5', exact: true }).click(); await page.getByRole('button', { name: 'Review reservation' }).click(); await expect(page.getByRole('status')).toContainText('Good'); });

test('full schema import rejects corrupt data and restores records', async ({ page }, testInfo) => { await openApp(page); await page.getByRole('button', { name: 'Settings', exact: true }).click(); const valid = testInfo.outputPath('valid-backup.json'); await writeFile(valid, JSON.stringify({ schemaVersion: 3, exportedAt: new Date().toISOString(), progress: { xp: 4321, goal: 20, minutes: 12, streak: 4, bestStreak: 6, placementLevel: 'B1' }, profile: { name: 'Mali', level: 'B1', learningGoal: 'Travel English' }, settings: { goal: 20, translation: true, sound: false, voice: 'UK English', speechRate: 1 }, lessonProgress: [{ lessonId: 'ordering-coffee', completed: true, xpAwarded: 20 }], vocabulary: [{ id: 'reservation', word: 'reservation', meaningThai: 'การจอง', definition: 'booking', example: 'I made a reservation.', status: 'Learning', nextReviewAt: new Date().toISOString(), interval: 1, ease: 2.5 }], reviews: [{ id: 'r1', vocabularyId: 'reservation', choice: 'Good', reviewedAt: new Date().toISOString() }], placement: { level: 'B1', answers: [0] }, dailyActivity: [{ date: '2026-08-31', minutes: 12, activities: 1 }] })); await page.locator('input[type=file]').setInputFiles(valid); await expect(page.getByRole('status')).toContainText('imported successfully'); await page.reload(); await expect(page.getByText('4,321')).toBeVisible(); await page.getByRole('button', { name: 'Settings', exact: true }).click(); await expect(page.getByRole('combobox', { name: 'English voice' })).toHaveValue('UK English'); await page.getByRole('button', { name: 'Vocabulary', exact: false }).click(); await expect(page.getByText('Learning')).toBeVisible(); const invalid = testInfo.outputPath('invalid-backup.json'); await writeFile(invalid, '{not-json'); await page.getByRole('button', { name: 'Settings', exact: true }).click(); await page.locator('input[type=file]').setInputFiles(invalid); await expect(page.getByRole('status')).toContainText('Import failed'); });

test('speech match control provides supported or graceful fallback feedback', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Practice', exact: true }).click(); await page.getByRole('button', { name: 'Check speech match' }).click(); await expect(page.getByRole('status')).toBeVisible(); });

test('dashboard metrics and vocabulary state rehydrate after reload', async ({ page }) => { await openApp(page); await page.getByRole('button', { name: 'Vocabulary', exact: false }).click(); await page.getByRole('button', { name: 'Review reservation' }).click(); await expect(page.getByText('Learning')).toBeVisible(); await page.reload(); await expect(page.getByText('Learning')).toBeVisible(); await page.getByRole('button', { name: 'Dashboard', exact: true }).click(); await expect(page.getByText('1 words in your word bank')).toBeVisible(); });
